-- RIVA WhatsApp bot — Supabase schema
-- Paste this whole file into the Supabase SQL editor and run it once.
-- Safe to re-run: every statement is idempotent.

-- ---------------------------------------------------------------- submissions
-- One row per finished presentation: the phone number, the message exactly as
-- the agent typed it, and the counters. Ids are generated by the bot so that
-- existing /p/<id> links keep working.
create table if not exists public.submissions (
  id              text primary key,
  created_at      timestamptz not null default now(),
  wa_id           text not null,               -- WhatsApp id (the phone number)
  phone           text,                        -- same, formatted as +2010...
  profile_name    text,                        -- WhatsApp display name
  message         text not null default '',    -- verbatim, never parsed
  run_id          text,                        -- upload folder for this submission
  views           integer not null default 0,
  last_viewed_at  timestamptz
);

create index if not exists submissions_wa_id_idx      on public.submissions (wa_id);
create index if not exists submissions_created_at_idx on public.submissions (created_at desc);

-- ---------------------------------------------------------------- images
-- One row per uploaded file, linked to the submission (and so to the phone
-- number) by submission_id. Deleting a submission removes its image rows.
create table if not exists public.submission_images (
  id             bigint generated always as identity primary key,
  submission_id  text not null references public.submissions (id) on delete cascade,
  kind           text not null check (kind in ('photo', 'floorplan')),
  position       integer not null,             -- order the agent sent them in
  storage_path   text not null,                -- path inside the storage bucket
  mime_type      text,
  bytes          integer,
  created_at     timestamptz not null default now(),
  unique (submission_id, kind, position)
);

create index if not exists submission_images_submission_idx on public.submission_images (submission_id);

-- ---------------------------------------------------------------- sessions
-- In-progress conversations. Holding these in Postgres instead of memory means
-- a restart mid-conversation doesn't lose the photos already sent, and lets you
-- run more than one instance of the bot.
create table if not exists public.sessions (
  wa_id         text primary key,
  profile_name  text,
  step          text not null default 'IDLE',
  run_id        text,
  lang          text not null default 'en',
  message       text not null default '',
  images        jsonb not null default '[]'::jsonb,
  floorplans    jsonb not null default '[]'::jsonb,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists sessions_touch_updated_at on public.sessions;
create trigger sessions_touch_updated_at
  before update on public.sessions
  for each row execute function public.touch_updated_at();

-- ---------------------------------------------------------------- export view
-- What the Excel export reads: one row per submission with its file counts.
create or replace view public.submission_export as
select
  s.id,
  s.created_at,
  s.phone,
  s.profile_name,
  s.message,
  count(*) filter (where i.kind = 'photo')     as photo_count,
  count(*) filter (where i.kind = 'floorplan') as floorplan_count,
  s.views
from public.submissions s
left join public.submission_images i on i.submission_id = s.id
group by s.id
order by s.created_at desc;

-- ---------------------------------------------------------------- storage
-- Bucket for the uploaded photos. Public means the presentation pages can use
-- plain CDN urls; the paths contain a random run id, so they are unguessable.
-- Flip `public` to false if you would rather the bot hand out signed urls.
insert into storage.buckets (id, name, public)
values ('listings', 'listings', true)
on conflict (id) do nothing;

-- ---------------------------------------------------------------- lockdown
-- RLS on, and deliberately no policies: nothing reaches these tables with the
-- anon key. The bot talks to them with the service_role key, which bypasses RLS
-- and must stay on the server, never in a browser.
alter table public.submissions       enable row level security;
alter table public.submission_images enable row level security;
alter table public.sessions          enable row level security;
